# Generated by Django 5.0.8 on 2026-04-15 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=30, unique=True)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_producto', to='Proveedor.proveedor_pxn')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleSolicitudProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Videojuego', 'Videojuego'), ('Consola', 'Consola'), ('Control', 'Control'), ('Accesorio', 'Accesorio')], max_length=20)),
                ('cantidad', models.IntegerField(default=1)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Solicitud_Productos.solicitudproducto')),
            ],
        ),
    ]
