# Generated by Django 5.0.8 on 2026-04-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntradaSalidas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
