# Generated by Django 5.0.8 on 2026-04-14 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
        ('Sucursal', '0001_initial'),
        ('EntradaSalidas', '0002_alter_entrada_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('unidad_medida', models.CharField(choices=[('kg', 'kg'), ('pieza', 'pieza'), ('caja', 'caja'), ('litro', 'litro')], max_length=10)),
                ('fecha', models.DateField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.producto_gb')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='Sucursal.sucursal')),
            ],
        ),
    ]
