# Generated by Django 5.2.10 on 2026-03-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor_pxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_prov', models.CharField(max_length=50)),
                ('nombre_prov', models.CharField(max_length=50)),
                ('contacto_prov', models.TextField(max_length=100)),
            ],
        ),
    ]
