# Generated by Django 5.1 on 2026-03-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal_pxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_suc', models.CharField(max_length=100, verbose_name='Nombre de la Sucursal')),
                ('direccion_suc', models.CharField(max_length=200, verbose_name='Dirección')),
                ('ciudad_suc', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('telefono_suc', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('encargado_suc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Encargado')),
                ('email_suc', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('horario_suc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Horario')),
                ('estado_suc', models.CharField(default='Activo', max_length=20, verbose_name='Estado')),
                ('empleados_suc', models.IntegerField(default=0, verbose_name='Número de Empleados')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursales',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
