<<<<<<< HEAD
# Generated by Django 5.1 on 2026-03-11 05:37
=======
# Generated by Django 5.0.8 on 2026-03-11 17:03
>>>>>>> bab294d71edd8fa96fbef62573f93678978f6ea2

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Sucursal_pxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_suc', models.CharField(max_length=100, verbose_name='Nombre de la Sucursal')),
                ('direccion_suc', models.CharField(max_length=200, verbose_name='Dirección')),
                ('ciudad_suc', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('telefono_suc', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('encargado_suc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Encargado')),
                ('email_suc', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('horario_suc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Horario')),
                ('estado_suc', models.CharField(default='Activo', max_length=20, verbose_name='Estado')),
                ('empleados_suc', models.IntegerField(default=0, verbose_name='Número de Empleados')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursales',
                'ordering': ['-fecha_registro'],
            },
=======
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('encargado', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('horario', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
>>>>>>> bab294d71edd8fa96fbef62573f93678978f6ea2
        ),
    ]
