# Generated by Django 5.1 on 2026-03-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal_pxn',
            options={},
        ),
    ]
