# Generated by Django 5.1 on 2026-03-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursal', '0002_alter_sucursal_pxn_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal_pxn',
            name='fecha_registro',
        ),
        migrations.AlterField(
            model_name='sucursal_pxn',
            name='ciudad_suc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sucursal_pxn',
            name='direccion_suc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sucursal_pxn',
            name='email_suc',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal_pxn',
            name='empleados_suc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sucursal_pxn',
            name='encargado_suc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal_pxn',
            name='estado_suc',
            field=models.CharField(default='Activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='sucursal_pxn',
            name='horario_suc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal_pxn',
            name='nombre_suc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sucursal_pxn',
            name='telefono_suc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='sucursal_pxn',
            table='sucursal',
        ),
    ]
